### ISSUE TITLE
Unable to resolve module underscore

### ISSUE THREAD

**Issue by smooJitter** [meteor-factory/react-native-meteor-starter#1]
I'm getting a red screen in the simulator with the following error:

Unable to resolve module underscore from /Users/me/react-native-meteor-starter-develop/Starter/app/config/db/lib/ddpClient.js: Unable to find this module in its module map or any of the node modules directories under /User/node_modules/underscore and its parent directories.

**Comment by yogiben** [comment]
@smooJitter just update `package.json`. Please check now.

**Comment by yogiben** [comment]
Pretty sure this is solved.
